AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Lambda events triggered by S3. Publish to SNS if applicable."

Resources:
  ReceiverFailover:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: receiver_failover/
      Handler: receiver_failover.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:111111111111:some-topic
          PROVIDERS_TO_PROCESS: "lrfp, vt3, ah"